### ISSUE TITLE
Can't upload a model of an existing version

### ISSUE THREAD

**Issue by MorVilozni** [IQSS/DataTaggingServer#26] opened 2017-08-07 20:05 UTC
When uploading a new zip to an existing version - 
the server remaining on 'processing'

**Comment by michbarsinai** [comment] 2017-08-20 06:57
Might be caused by a bug solved by 2.6.3, so do #31 first.

**Comment by michbarsinai** [comment] 2017-10-27 13:25
Fixed. Late closing.

**Closed by michbarsinai** 2017-10-27 13:25 UTC
Labels: bug
